[package]
name = "nysa-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.21"
proc-macro2 = "1.0.43"
syn = { version = "1.0.99", features = ["full"] }
project-root = "0.2.2"
nysa = { path = "../nysa" }

[dev-dependencies]
near-sdk = "4.0.0"
