[package]
name = "example-fibonacci"
version = "0.1.0"
edition = "2021"

[dependencies]
near-sdk = "4.0.0"
nysa-macro = { path = "../nysa-macro" }

[lib]
crate-type = ["cdylib"]

[features]
default = ["solidity"]
solidity = []
near = []
