[package]
name = "odra-example-status"
version = "0.1.0"
edition = "2021"

[dependencies]
odra = { path = "../../../../odra/core", default-features = false }

[features]
default = ["mock-vm"]
mock-vm = ["odra/mock-vm"]
casper = ["odra/casper"]
