[package]
name = "odra-owned-token"
version = "0.1.0"
edition = "2021"

[dependencies]
odra = { version = "0.8.0", path = "../../../../odra/odra" }

[dev-dependencies]
odra-test = { version = "0.8.0", path = "../../../../odra/odra-test" }
