[package]
name = "nysa"
version = "0.1.0"
edition = "2021"

[dependencies]
solidity-parser = { path = "../solidity-parser" }
c3-lang-parser = { git = "https://github.com/odradev/c3-lang.git", branch = "feature/near-support" }
c3-lang-linearization = { git = "https://github.com/odradev/c3-lang.git", branch = "feature/near-support" }
quote = "1.0.21"
syn = "1.0.99"
proc-macro2 = "1.0.43"

[dev-dependencies]
pretty_assertions = "1.2"
